export default {
  FETCH_JOKES_REQUEST: "FETCH_JOKES_REQUEST",
  FETCH_JOKES_SUCCESS: "FETCH_JOKES_SUCCESS",
  FETCH_JOKES_FAILURE: "FETCH_JOKES_FAILURE",
  SELECT_CANDIDATE: "SELECT_CANDIDATE",
  RE_ARRANGE_SELECTED_CANDIDATES: "RE_ARRANGE_SELECTED_CANDIDATES",
  SET_CANDIDATES: "SET_CANDIDATES",
  OBAMA: "Barack Obama",
  TRUMP: "Donald Trump"
};
